---
name: App-ZofCMS-Plugin-InstalledModuleChecker
version: 0.0102
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: utility plugin to check for installed modules on the server
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::InstalledModuleChecker:
    file: lib/App/ZofCMS/Plugin/InstalledModuleChecker.pm
    version: 0.0102
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
